# Test against the latest version of this Node.js version
environment:
  nodejs_version: "8"

cache: 
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - node_modules                    # local npm modules
  - '%APPDATA%\npm-cache'

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - ps: .\build.ps1

before_build:
  - nuget restore samples\GitHub\output\OutTest.sln

test: off

build:
  project: samples\GitHub\output\OutTest.sln

after_build:
  - ps: .\publish.ps1